name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        env:
          MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          MYSQL_ENDPOINT: ${{ secrets.MYSQL_ENDPOINT }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          TEST_TOKEN: ${{secrets.TEST_TOKEN }}
          TESTER_EMAIL: ${{secrets.TESTER_EMAIL}}
          SPRING_PORT: ${{ secrets.SPRING_PORT }}
          SONAR: ${{ secrets.SONAR }}
          JWT_SECRET: ${{ secrets.JWT }}
      - name: Sonarqube
        run: mvn verify sonar:sonar
        env:
          MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
          MYSQL_ENDPOINT: ${{ secrets.MYSQL_ENDPOINT }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          TEST_TOKEN: ${{secrets.TEST_TOKEN }}
          TESTER_EMAIL: ${{secrets.TESTER_EMAIL}}
          SPRING_PORT: ${{ secrets.SPRING_PORT }}
          SONAR: ${{ secrets.SONAR }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          JWT_SECRET: ${{ secrets.JWT }}